name = "YauScape"
uuid = "4cb3e412-1fa2-4c01-b24c-9b4d3fbfe773"
authors = ["Eito Yoneyama"]
version = "1.0.0-DEV"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
Plots = "1.40.9"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
